WANDB_ENTROPY_COMPARE_PROJECT = "hate-detect-compare-EAR"
WANDB_MODEL_COMPARE_PROJECT = "hate-detect-model-compare"

EPOCHS = 20
HEAD_LEARNING_RATE = 1e-3
FINE_TUNE_LEARNING_RATE = 1e-5
PHI = 1e-3
DROPOUT_RATE = 0.1

